version: "3.8"

services:
  app:
    image: iagoqueiroz/symfony-demo
    build:
      context: .
      target: app

  web:
    image: nginx:1.21
    build:
      context: .
      target: web
    depends_on:
      - app
