apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
spec:
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      containers:
      - name: symfony-app
        image: iagoqueiroz/symfony-demo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
